# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20151125_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='category',
            field=models.CharField(choices=[('WELCOME', 'A new user has joined'), ('OLD', 'A legacy notification'), ('TEST', 'A test notification')], default='OLD', max_length=255),
        ),
    ]
